# Generated by Django 3.1.7 on 2021-03-17 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
