# Generated by Django 3.1.7 on 2021-03-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210322_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
