# Generated by Django 3.1.7 on 2021-03-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
