# Generated by Django 3.1.7 on 2021-03-18 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='review',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=300, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
