# Generated by Django 3.1.7 on 2021-03-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_photo'),
        ('main', '0009_auto_20210319_1815'),
    ]

    operations = [
    ]
