# Generated by Django 3.1.7 on 2021-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique_for_date='publish'),
        ),
    ]
