# Generated by Django 3.1.7 on 2021-03-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=240)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
